# Generated by Django 5.1 on 2024-08-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
